server:
  port: 8072
spring:
  data:
    redis:
      timeout: 1s
      connect-timeout: 2s
      host: localhost
      port: 6379
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
    config:
      enabled: false
    kubernetes:
      discovery:
        enabled: false
      config:
        enabled: false
  kafka:
    bootstrap-servers: http://localhost:9092

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

logging:
  level:
    io:
      github:
        susimsek:
          gatewayserver: DEBUG
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
