spring:
  application:
    name: gateway-server
  config:
    import: optional:configserver:http://localhost:8071/
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  kafka:
    bootstrap-servers: http://localhost:9092
  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: false
#          lower-case-service-id: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
    kubernetes:
      loadbalancer:
        mode: service
      discovery:
        enabled: true
        all-namespaces: true
    discovery:
      client:
        health-indicator:
          enabled: false
  data:
    redis:
      timeout: 1s
      connect-timeout: 2s
      host: localhost
      port: 6379
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:7080/realms/master/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
    enabled: false

info:
  app:
    name: "gateway-server"
    description: "Eazy Bank Gateway Server Application"
    version: "1.0.0"

server:
  port: 8072

logging:
  level:
    io:
      github:
        susimsek:
          gatewayserver: DEBUG
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000