name: Test, Sonar and deploy.

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build-and-analyse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'
      - name: Print Java Version
        run:  java -version
      - name: Download Dependencies
        run: mvn dependency:go-offline
      - name: Test
        run: mvn -ntp clean verify