spring:
  cloud:
    config:
      enabled: false
  kafka:
    bootstrap-servers: http://localhost:9092
  security:
    user:
      name: easybank
      password: root
      roles: USER, ADMIN
    content-security-policy: "script-src 'self'"

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
