spring:
  cloud:
    config:
      enabled: false
  kafka:
    bootstrap-servers: http://localhost:9092
  security:
    user:
      name: easybank
      password: root
      roles: USER, ADMIN
    content-security-policy: "script-src 'self'"

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
