controller:
  replicaCount: 1


listeners:
  client:
    protocol: PLAINTEXT
  controller:
    protocol: PLAINTEXT
  interbroker:
    protocol: PLAINTEXT
  external:
    protocol: PLAINTEXT

kraft:
  enabled: true
  clusterId: s_vb8yLzRnyOVW3Ko2mUbg