config-server:
  enabled: true
  spring:
    profiles:
      active: default

eureka-server:
  enabled: true
  spring:
    profiles:
      active: default

gateway-server:
  enabled: true
  spring:
    profiles:
      active: default

account:
  spring:
    profiles:
      active: default
    liquibase:
      contexts: dev

loan:
  spring:
    profiles:
      active: default
    liquibase:
      contexts: dev

card:
  spring:
    profiles:
      active: default
    liquibase:
      contexts: dev

message:
  spring:
    profiles:
      active: default