admin:
  user: admin
  password: root

datasources:
    secretDefinition:
        apiVersion: 1
        deleteDatasources:
            - name: Prometheus
            - name: Loki
            - name: Tempo
        datasources:
            - name: Prometheus
              type: prometheus
              uid: prometheus
              url: http://prometheus-kube-prometheus-prometheus:9090
              access: proxy
              orgId: 1
              basicAuth: false
              isDefault: false
              version: 1
              editable: true
              jsonData:
                  httpMethod: GET
            - name: Tempo
              type: tempo
              uid: tempo
              url: http://tempo-grafana-tempo-query-frontend:3200
              access: proxy
              orgId: 1
              basicAuth: false
              isDefault: false
              version: 1
              editable: true
              jsonData:
                  httpMethod: GET
                  serviceMap:
                      datasourceUid: 'prometheus'
            - name: Loki
              type: loki
              uid: loki
              access: proxy
              orgId: 1
              editable: true
              url: http://loki-grafana-loki-gateway:80
              jsonData:
                  httpHeaderName1: "X-Scope-OrgID"
                  derivedFields:
                      - datasourceUid: tempo
                        matcherRegex: "\\[.+,(.+),.+\\]"
                        name: TraceID
                        url: '$${__value.raw}'
              secureJsonData:
                  httpHeaderValue1: "tenant1"