# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: gateway-server-deployment
serviceName: gateway-server
appLabel: gateway-server
appName: gateway-server

replicaCount: 1

image:
  repository: suayb/gateway-server
  tag: s17

containerPort: 8072

service:
  type: LoadBalancer
  port: 8072
  targetPort: 8072

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: false
discovery_enabled: true
resouceserver_enabled: true
tracing_enabled: true
kafka_enabled: true
database_enabled: false
redis_enabled: true