config-server:
  enabled: true
  spring:
    profiles:
      active: qa

eureka-server:
  enabled: true
  spring:
    profiles:
      active: qa

gateway-server:
  enabled: true
  spring:
    profiles:
      active: qa

account:
  spring:
    profiles:
      active: qa
    liquibase:
      contexts: qa

loan:
  spring:
    profiles:
      active: qa
    liquibase:
      contexts: qa

card:
  spring:
    profiles:
      active: qa
    liquibase:
      contexts: qa

message:
  spring:
    profiles:
      active: qa