---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: spring-cloud-kubernetes-discoveryserver
      labels:
        app: spring-cloud-kubernetes-discoveryserver
    spec:
      selector:
        app: spring-cloud-kubernetes-discoveryserver
      type: ClusterIP
      ports:
        - name: http
          targetPort: 8761
          port: 80
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: spring-cloud-kubernetes-discoveryserver
      labels:
        app: spring-cloud-kubernetes-discoveryserver
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: spring-cloud-kubernetes-discoveryserver:view
      labels:
        app: spring-cloud-kubernetes-discoveryserver
    roleRef:
      kind: Role
      name: namespace-reader
      apiGroup: rbac.authorization.k8s.io
    subjects:
      - kind: ServiceAccount
        name: spring-cloud-kubernetes-discoveryserver
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: namespace-reader
      namespace: default
    rules:
      - apiGroups: ["", "extensions", "apps"]
        resources: ["services", "endpoints", "pods"]
        verbs: ["get", "list", "watch"]
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: spring-cloud-kubernetes-discoveryserver-deployment
    spec:
      selector:
        matchLabels:
          app: spring-cloud-kubernetes-discoveryserver
      template:
        metadata:
          labels:
            app: spring-cloud-kubernetes-discoveryserver
        spec:
          serviceAccountName: spring-cloud-kubernetes-discoveryserver
          containers:
          - name: spring-cloud-kubernetes-discoveryserver
            image: springcloud/spring-cloud-kubernetes-discoveryserver:3.0.4
            imagePullPolicy: IfNotPresent
            readinessProbe:
              httpGet:
                port: 8761
                path: /actuator/health/readiness
              initialDelaySeconds: 100
              periodSeconds: 30  
            livenessProbe:
              httpGet:
                port: 8761
                path: /actuator/health/liveness
              initialDelaySeconds: 100
              periodSeconds: 30  
            ports:
            - containerPort: 8761