apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-server
  namespace: default
data:
  application.yml: |-
    server:
      port: 8070
      shutdown: graceful
    
    eureka:
      instance:
        hostname: localhost
      client:
        fetchRegistry: false
        registerWithEureka: false
        serviceUrl:
          defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    
    spring:
      main:
        allow-bean-definition-overriding: true
      output:
        ansi:
          enabled: always
    
    management:
      endpoints:
        web:
          exposure:
            include: "*"
      health:
        readiness-state:
          enabled: true
        liveness-state:
          enabled: true
      endpoint:
        health:
          probes:
            enabled: true
      metrics:
        tags:
          application: ${spring.application.name}
      tracing:
        sampling:
          probability: 1.0
        enabled: true
