spring:
  application:
    name: config-server
  profiles:
    # active: native
    active: git
  cloud:
    config:
      server:
        # native:
          # search-locations: classpath:config
       git:
         uri: https://github.com/susimsek/microservice-config.git
         default-label: main
         timeout: 5
         clone-on-start: true
         force-pull: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  kafka:
    bootstrap-servers: http://localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
    enabled: false
encrypt:
  key: 45D81EC1EF61DF9AD8D3E5BB397F9

server:
  port: 8071

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'