{{- if .Values.autoscaling.enabled }}
apiVersion: {{ include "spring-cloud-kubernetes-configserver.capabilities.hpa.apiVersion" ( dict "context" $ ) }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "spring-cloud-kubernetes-configserver.fullname" . }}
  namespace: {{ include "spring-cloud-kubernetes-configserver.namespace" . | quote }}
  labels: {{- include "spring-cloud-kubernetes-configserver.labels" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: spring-cloud-kubernetes-configserver
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "spring-cloud-kubernetes-configserver.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: {{ include "spring-cloud-kubernetes-configserver.capabilities.deployment.apiVersion" . }}
    kind: Deployment
    name: {{ template "spring-cloud-kubernetes-configserver.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.targetCPU }}
    - type: Resource
      resource:
        name: cpu
        {{- if semverCompare "<1.23-0" (include "spring-cloud-kubernetes-configserver.capabilities.kubeVersion" .) }}
        targetAverageUtilization: {{ .Values.autoscaling.targetCPU }}
        {{- else }}
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPU }}
        {{- end }}
    {{- end }}
    {{- if .Values.autoscaling.targetMemory }}
    - type: Resource
      resource:
        name: memory
        {{- if semverCompare "<1.23-0" (include "spring-cloud-kubernetes-configserver.capabilities.kubeVersion" .) }}
        targetAverageUtilization: {{ .Values.autoscaling.targetMemory }}
        {{- else }}
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetMemory }}
        {{- end }}
    {{- end }}
{{- end }}