{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "spring-cloud-kubernetes-configserver.serviceAccountName" . }}
  namespace: {{ include "spring-cloud-kubernetes-configserver.namespace" . | quote }}
  labels: {{- include "spring-cloud-kubernetes-configserver.labels" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: spring-cloud-kubernetes-configserver
    {{- if .Values.serviceAccount.extraLabels }}
    {{- include "spring-cloud-kubernetes-configserver.tplvalues.render" (dict "value" .Values.serviceAccount.extraLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if or .Values.serviceAccount.annotations .Values.commonAnnotations }}
  {{- $annotations := include "spring-cloud-kubernetes-configserver.tplvalues.merge" ( dict "values" ( list .Values.serviceAccount.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "spring-cloud-kubernetes-configserver.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}