apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "debezium.fullname" . | quote }}
  namespace: {{ include "debezium.namespace" . | quote }}
  labels: {{- include "debezium.labels" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: debezium
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "debezium.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  REST_PORT: {{ .Values.containerPorts.http | quote }}
  REST_ADVERTISED_HOST_NAME: "connect"
  BOOTSTRAP_SERVERS: {{ .Values.kafka.bootstrapServers | quote }}
  CONFIG_STORAGE_TOPIC: {{ .Values.connect.config.storage.topic | quote }}
  OFFSET_STORAGE_TOPIC: {{ .Values.connect.offset.storage.topic | quote }}
  STATUS_STORAGE_TOPIC: {{ .Values.connect.status.storage.topic | quote }}
  CONFIG_STORAGE_REPLICATION_FACTOR: {{ .Values.connect.config.storage.replication.factor | quote }}
  OFFSET_STORAGE_REPLICATION_FACTOR: {{ .Values.connect.offset.storage.replication.factor | quote }}
  STATUS_STORAGE_REPLICATION_FACTOR: {{ .Values.connect.status.storage.replication.factor | quote }}
  KEY_CONVERTER: {{ .Values.connect.keyConverter | quote }}
  VALUE_CONVERTER: {{ .Values.connect.valueConverter | quote }}
  GROUP_ID: {{ .Values.connect.groupId | quote }}
  CONNECTOR_CLIENT_CONFIG_OVERRIDE_POLICY: "all"