name: Account build.

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/account
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'
      - name: Print Java Version
        run:  java -version
      - name: Download Dependencies
        run: mvn dependency:go-offline
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Test
        run: mvn -ntp clean verify
      - name: Quality Analysis
        run: mvn -ntp -Psonar initialize sonar:sonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}